### ISSUE TITLE
LINEリッチメニューのTypeScript定義化とGitHub Actions手動デプロイの自動化

### ISSUE THREAD

**Issue by 709sakata** [Hopin-inc/civicship-api#251]
## 概要

LINEリッチメニューの生成・設定を手動運用から自動化し、TypeScriptでコード管理できるようにする。

---

## 現状の課題

- リッチメニューの生成・設定が `scripts/richmenu/{community}/setup_richmenu.sh` による手動実行
- 環境間（dev/stg/prod）の同期や再現が困難
- 設定ミスや漏れのリスクがあり、デプロイごとに人手を介する必要がある
- メニュー構成をコードで管理できず、変更の履歴管理・再展開ができない状態
- シェルスクリプトから `t_community_line_rich_menus` への登録は自動化されておらず、別途手動 or 他の手段に依存している

---

### アーキテクチャ

**コミュニティ別ディレクトリ構成** を採用：

```
src/infrastructure/richmenu/
├── neo88/                     # コミュニティ別ディレクトリ
│   ├── definitions/
│   │   ├── admin.ts
│   │   └── public.ts
│   ├── images/
│   │   ├── admin_menu.png
│   │   └── public_menu.png
│   └── index.ts               # コミュニティのエクスポート
├── izu/
│   ├── definitions/
│   │   ├── admin.ts
│   │   ├── user-use.ts
│   │   ├── user-earn.ts
│   │   ├── user-join.ts
│   │   ├── public-use.ts
│   │   ├── public-earn.ts
│   │   └── public-join.ts
│   ├── images/
│   │   ├── admin_menu.png
│   │   ├── user_use.png
│   │   └── ...
│   └── index.ts
├── dais/
│   ├── definitions/
│   ├── images/
│   └── index.ts
├── kibotcha/
│   ├── definitions/
│   ├── images/
│   └── index.ts
├── types.ts                   # RichMenuDefinition型定義（共通）
├── utils.ts                   # プレースホルダ置換などのユーティリティ（共通）
└── deployer.ts                # デプロイロジック（共通）
```

**この構成を選んだ理由:**
1. **CLI との整合性** - `--community=izu` で指定するので、`richmenu/izu/` にマッピングする方が自然
2. **作業単位との一致** - 「izu のメニューを調整」するとき、izu ディレクトリ内で完結する
3. **既存スクリプトとの一貫性** - `scripts/richmenu/neo88/` と同じメンタルモデル
4. **定義と画像の密結合** - 各定義が参照する画像が同じコミュニティディレクトリ内にある

### 実行方式

**GitHub Actions 手動トリガー（workflow_dispatch）** を採用

- 通常のデプロイ（develop/masterへのpush）では実行されない
- リッチメニューを変更したい時だけ、GitHub上で「Run workflow」ボタンを押して実行
- 既存のCI/CDパイプラインには影響を与えない

**理由:**
- リッチメニューの変更頻度は低い（毎デプロイで変わるものではない）
- LINE APIへの不要な呼び出しを避けられる
- 画像アップロードを含むため処理時間がかかる

---

### 方針

**各 `LineRichMenuType` につき、1つの「ロール起点メニュー」のみを `t_community_line_rich_menus` に保存する。**

タブ切り替え用のメニュー（izu の use/earn/join など）は LINE 側にデプロイするが、DB には保存しない。LINE 側の `richmenuswitch` アクションで内部的に切り替わるため、バックエンドが個別の `richMenuId` を知る必要がない。

### 具体例（izu の場合）

| メニュー | alias | DB保存 | 用途 |
|----------|-------|--------|------|
| admin.ts | `admin-menu` | `ADMIN` として保存 | 管理者ロールの起点メニュー |
| public-use.ts | `public-use` | `PUBLIC` として保存 | 一般ユーザーロールの起点メニュー |
| public-earn.ts | `public-earn` | 保存しない | タブ切り替え用（LINE側のみ） |
| public-join.ts | `public-join` | 保存しない | タブ切り替え用（LINE側のみ） |
| user-use.ts | `user-use` | 保存しない | タブ切り替え用（LINE側のみ） |
| user-earn.ts | `user-earn` | 保存しない | タブ切り替え用（LINE側のみ） |
| user-join.ts | `user-join` | 保存しない | タブ切り替え用（LINE側のみ） |

### 理由

- 現在の `NotificationService.switchRichMenuByRole()` は `ADMIN` または `PUBLIC` のみを使用
- `LineRichMenuType.USER` は現時点で未使用
- タブメニューのエイリアス（user-use, user-earn 等）はバックエンドコードで参照されていない
- 既存の Prisma スキーマ（`@@unique([configId, type])`）をそのまま活用可能

---

### 1. TypeScript型定義

**型定義 (`types.ts`):**
```typescript
import { LineRichMenuType } from "@prisma/client";
import { MessagingApiClient } from "@line/bot-sdk";
import { PrismaClient } from "@prisma/client";

// Discriminated Union で型安全性を確保
type UriAction = {
  type: "uri";
  label?: string;
  uri: string;  // ${LIFF_BASE_URL} プレースホルダ可
};

type RichMenuSwitchAction = {
  type: "richmenuswitch";
  richMenuAliasId: string;
  data: string;
};

type PostbackAction = {
  type: "postback";
  label?: string;
  data: string;
};

export type RichMenuAction = UriAction | RichMenuSwitchAction | PostbackAction;

export interface RichMenuArea {
  bounds: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
  action: RichMenuAction;
}

export interface RichMenuDefinition {
  size: { width: 2500; height: 1686 | 843 };
  selected: boolean;
  name: string;
  chatBarText: string;
  areas: RichMenuArea[];
  
  // 画像パス（コミュニティディレクトリ基準、例: "images/admin_menu.png"）
  imagePath: string;
  
  // LINE APIエイリアス（例: "admin-menu"）
  alias: string;
  
  // DB保存対象の場合のみ指定（ロール起点メニュー）
  // 指定がない場合はLINE側にのみデプロイ
  roleEntryFor?: LineRichMenuType;
  
  // デフォルトメニューとして全ユーザーに設定するか
  isDefault?: boolean;
}

export interface CommunityRichMenuConfig {
  communityId: string;  // DB上の community.id に対応
  menus: RichMenuDefinition[];
}

// デプロイコンテキスト（依存性の明示化）
export interface DeployRichMenuContext {
  lineClient: MessagingApiClient;
  prisma: PrismaClient;
  communityBasePath: string;
  liffBaseUrl: string;
  configId: string;
}

// デプロイ結果（サマリー出力用）
export interface DeployMenuResult {
  alias: string;
  richMenuId: string;
  dbSaved: boolean;
  isDefault: boolean;
}

export interface DeploySummary {
  community: string;
  menus: DeployMenuResult[];
  timestamp: string;
}
```

**定義ファイル例 (`izu/definitions/admin.ts`):**
```typescript
import { RichMenuDefinition } from "../../types";

export const adminMenu: RichMenuDefinition = {
  size: { width: 2500, height: 1686 },
  selected: true,
  name: "管理者メニュー",
  chatBarText: "メニューを開く",
  areas: [
    {
      bounds: { x: 95, y: 146, width: 980, height: 318 },
      action: {
        type: "richmenuswitch",
        richMenuAliasId: "user-use",
        data: "switch:user-use"
      }
    },
    {
      bounds: { x: 0, y: 0, width: 2500, height: 843 },
      action: {
        type: "uri",
        label: "管理者ホーム",
        uri: "${LIFF_BASE_URL}/admin/wallet"
      }
    }
    // ... 他のエリア
  ],
  imagePath: "images/admin_menu.png",  // コミュニティディレクトリ基準
  alias: "admin-menu",
  roleEntryFor: "ADMIN"  // ← DB保存対象
};
```

**コミュニティエクスポート (`izu/index.ts`):**
```typescript
import { adminMenu } from "./definitions/admin";
import { publicUseMenu } from "./definitions/public-use";
import { publicEarnMenu } from "./definitions/public-earn";
import { publicJoinMenu } from "./definitions/public-join";
import { userUseMenu } from "./definitions/user-use";
import { userEarnMenu } from "./definitions/user-earn";
import { userJoinMenu } from "./definitions/user-join";
import { CommunityRichMenuConfig } from "../types";

export const izuConfig: CommunityRichMenuConfig = {
  communityId: "izu",  // community.slug に対応
  menus: [
    adminMenu,
    publicUseMenu,
    publicEarnMenu,
    publicJoinMenu,
    userUseMenu,
    userEarnMenu,
    userJoinMenu,
  ],
};
```

### 2. プレースホルダ置換ユーティリティ

**`utils.ts`:**
```typescript
import { RichMenuDefinition } from "./types";

export function resolvePlaceholders(
  definition: RichMenuDefinition,
  context: { liffBaseUrl: string }
): RichMenuDefinition {
  const resolved = JSON.parse(JSON.stringify(definition));
  
  for (const area of resolved.areas) {
    if (area.action.type === "uri" && area.action.uri) {
      area.action.uri = area.action.uri.replace(
        /\$\{LIFF_BASE_URL\}/g,
        context.liffBaseUrl
      );
    }
  }
  
  return resolved;
}

// LINE API エラーが 404 Not Found かどうかを判定
function isNotFoundError(error: unknown): boolean {
  // LINE Messaging API クライアントのエラー型に応じて実装
  // HTTP 404 / NOT_FOUND 相当のみ true を返す
  if (error && typeof error === "object" && "statusCode" in error) {
    return (error as { statusCode: number }).statusCode === 404;
  }
  return false;
}

// 存在しない alias の削除エラーを安全に無視
export async function safeDeleteAlias(
  client: MessagingApiClient,
  alias: string
): Promise<void> {
  try {
    await client.deleteRichMenuAlias(alias);
  } catch (e: unknown) {
    if (isNotFoundError(e)) {
      console.info(`Alias "${alias}" not found, skipping deletion`);
      return;
    }
    throw e;
  }
}

// 存在しない richMenu の削除エラーを安全に無視
export async function safeDeleteRichMenu(
  client: MessagingApiClient,
  richMenuId: string
): Promise<void> {
  try {
    await client.deleteRichMenu(richMenuId);
  } catch (e: unknown) {
    if (isNotFoundError(e)) {
      console.info(`RichMenu "${richMenuId}" not found, skipping deletion`);
      return;
    }
    throw e;
  }
}
```

### 3. デプロイスクリプト (`deployer.ts`)

**設計方針:**
- CLI / コマンド側が `DeployRichMenuContext` を組み立てる責務を持つ
- `deployRichMenus` はコンテキストを受け取るだけで、依存性の生成は行わない
- これによりユニットテストが容易になる

**処理フロー:**
```typescript
import {
  DeployRichMenuContext,
  RichMenuDefinition,
  DeployMenuResult,
  DeploySummary,
} from "./types";
import { resolvePlaceholders, safeDeleteAlias } from "./utils";

async function deployRichMenus(
  ctx: DeployRichMenuContext,
  menus: RichMenuDefinition[]
): Promise<DeployMenuResult[]> {
  const { lineClient, prisma, communityBasePath, liffBaseUrl, configId } = ctx;
  const results: DeployMenuResult[] = [];

  for (const menu of menus) {
    // 1. プレースホルダ置換
    const resolved = resolvePlaceholders(menu, { liffBaseUrl });

    // 2. 既存エイリアス・メニューの削除（404 は無視）
    await safeDeleteAlias(lineClient, menu.alias);

    // 3. 新規リッチメニュー作成
    const richMenuId = await lineClient.createRichMenu(
      toLineRichMenuRequest(resolved)
    );

    // 4. 画像アップロード（コミュニティディレクトリ基準で解決）
    const imagePath = path.resolve(communityBasePath, menu.imagePath);
    await uploadRichMenuImage(lineClient, richMenuId, imagePath);

    // 5. エイリアス作成
    await lineClient.createRichMenuAlias({
      richMenuAliasId: menu.alias,
      richMenuId,
    });

    // 6. DB保存（ロール起点メニューのみ）
    let dbSaved = false;
    if (menu.roleEntryFor) {
      await prisma.communityLineRichMenuConfig.upsert({
        where: {
          configId_type: {
            configId,
            type: menu.roleEntryFor,
          },
        },
        update: { richMenuId },
        create: {
          configId,
          type: menu.roleEntryFor,
          richMenuId,
        },
      });
      dbSaved = true;
    }

    // 7. デフォルトメニュー設定
    if (menu.isDefault) {
      await lineClient.setDefaultRichMenu(richMenuId);
    }

    results.push({
      alias: menu.alias,
      richMenuId,
      dbSaved,
      isDefault: menu.isDefault ?? false,
    });
  }

  return results;
}

// CLI エントリポイント例
async function main() {
  const communityId = parseArgs().community;

  // 1. DB から設定を取得
  const lineConfig = await getLineConfig(communityId);

  // 2. コンテキストを組み立て
  const ctx: DeployRichMenuContext = {
    lineClient: new MessagingApiClient({
      channelAccessToken: lineConfig.accessToken,
    }),
    prisma,
    communityBasePath: path.resolve(__dirname, communityId),
    liffBaseUrl: lineConfig.liffBaseUrl,
    configId: lineConfig.id,
  };

  // 3. メニュー定義を取得
  const config = await import(`./${communityId}`);
  const menus = config.default.menus;

  // 4. デプロイ実行
  const results = await deployRichMenus(ctx, menus);

  // 5. サマリー出力
  const summary: DeploySummary = {
    community: communityId,
    menus: results,
    timestamp: new Date().toISOString(),
  };

  // JSON ファイルに出力（GitHub Actions artifact 用）
  fs.writeFileSync(
    "richmenu-deploy-result.json",
    JSON.stringify(summary, null, 2)
  );

  console.log("Deploy completed:", summary);
}
```

**CLIインターフェース:**
```bash
# 特定コミュニティのみデプロイ
pnpm richmenu:deploy --community=neo88

# 全コミュニティをデプロイ
pnpm richmenu:deploy --all

# ドライラン（実際にはデプロイしない）
pnpm richmenu:deploy --community=izu --dry-run

# 詳細ログ出力
pnpm richmenu:deploy --community=izu --verbose
```

### 4. ドライラン出力

`--dry-run` 実行時に出力する情報:
- 対象 community / configId
- 各メニューごとの:
  - `name`, `alias`, `roleEntryFor`
  - 使用する画像パス（解決後の絶対パス）
  - DB保存対象かどうか
  - デフォルトメニューかどうか
- 実際の API 呼び出しはスキップ
- `--verbose` 併用時は LINE API に送信予定の payload も出力

### 5. GitHub Actions ワークフロー

**`.github/workflows/deploy-richmenu.yml`:**
```yaml
name: Deploy Rich Menu

on:
  workflow_dispatch:
    inputs:
      community:
        description: "Community ID (neo88, izu, dais, kibotcha, or all)"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - neo88
          - izu
          - dais
          - kibotcha
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - prod

# 同じ env/community の多重実行を防止
concurrency:
  group: richmenu-${{ inputs.environment }}-${{ inputs.community }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'prod' && 'co-creation-dao-prod' || 'dev' }}
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Connect to DB via jumpbox
        run: |
          gcloud compute ssh ${{ secrets.JUMPBOX_INSTANCE_NAME }} \
            --tunnel-through-iap \
            --zone=${{ secrets.JUMPBOX_ZONE }} \
            --quiet -- -N -L 5432:localhost:5432 &

          # DB 疎通確認（最大 ~60 秒待機）
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 2>/dev/null; then
              echo "Database is ready"
              break
            fi
            echo "Waiting for database connection... ($i/30)"
            sleep 2
          done

      - name: Generate Prisma Client
        run: pnpm db:generate

      - name: Deploy Rich Menu
        env:
          DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}
        run: |
          if [ "${{ inputs.community }}" = "all" ]; then
            pnpm richmenu:deploy --all
          else
            pnpm richmenu:deploy --community=${{ inputs.community }}
          fi

      - name: Upload deploy summary
        uses: actions/upload-artifact@v4
        with:
          name: richmenu-deploy-${{ inputs.community }}-${{ inputs.environment }}
          path: richmenu-deploy-result.json
          retention-days: 30
```

**Environment と DB の対応:**
| environment | GitHub Environment | DB |
|-------------|-------------------|-----|
| dev | `dev` | dev用 Cloud SQL |
| prod | `co-creation-dao-prod` | prod用 Cloud SQL |

**注意:** `pg_isready` が利用できない環境では、`psql` など他の方法で疎通確認を行う。

---

### deployer.ts の責務

- LINE API を呼び出してリッチメニューを作成・更新
- 画像をアップロード
- エイリアスを設定
- **ロール起点メニューの `richMenuId` を `t_community_line_rich_menus` に反映**
- 実行結果サマリーを JSON 出力

### 既存コードの責務（変更なし）

- `NotificationService.switchRichMenuByRole()`:
  - メンバーシップのロールに応じて `LineRichMenuType` を決定（ADMIN or PUBLIC）
  - `CommunityConfigService.getLineRichMenuIdByType()` で DB から `richMenuId` を取得
  - LINE API `linkRichMenuIdToUser` でユーザーにメニューを紐付け

### パフォーマンス

**リクエスト時の処理は変更なし:**
- ロール切り替え時: 1回の DB 読み取り + 1回の LINE API 呼び出し
- 今回の自動化はデプロイ時のプロビジョニングパスのみを改善

---

### Phase 1: TypeScript定義ファイル作成
- [ ] `src/infrastructure/richmenu/types.ts` 型定義作成（`DeployRichMenuContext`, `DeploySummary` 含む）
- [ ] `src/infrastructure/richmenu/utils.ts` ユーティリティ作成（`safeDeleteAlias`, `safeDeleteRichMenu` 含む）
- [ ] 各コミュニティディレクトリ作成（`neo88/`, `izu/`, `dais/`, `kibotcha/`）
- [ ] 既存JSON（`scripts/richmenu/*/`）をTypeScriptに変換
- [ ] 画像ファイルを各コミュニティの `images/` に移動
- [ ] 各コミュニティの `index.ts` エクスポート作成

### Phase 2: デプロイスクリプト実装
- [ ] `src/infrastructure/richmenu/deployer.ts` 実装（`DeployRichMenuContext` を引数に取る設計）
- [ ] LINE API呼び出しロジック（作成、画像アップロード、エイリアス設定）
- [ ] DB保存ロジック（roleEntryFor がある場合のみ upsert）
- [ ] CLIインターフェース（`package.json` にスクリプト追加）
- [ ] ドライラン機能
- [ ] JSON サマリー出力機能

### Phase 3: GitHub Actions統合
- [ ] `.github/workflows/deploy-richmenu.yml` 作成
- [ ] DB トンネル待機ロジック（`pg_isready` ポーリング）
- [ ] `upload-artifact` による結果保存
- [ ] 動作確認（dev環境）

### Phase 4: クリーンアップ
- [ ] 旧スクリプト（`scripts/richmenu/`）の削除または非推奨化
- [ ] ドキュメント整備

---

### LINE API制限
- リッチメニュー作成: 1000件/分
- 画像: 10MB以下、2500x1686 または 2500x843 ピクセル

### エラーハンドリング
- 存在しない alias / richMenu の削除は info レベルでログを出して無視（404 Not Found）
- それ以外のエラーは throw して失敗とする
- メニュー作成失敗時はエラーログを出力して処理継続
- 全体の成功/失敗サマリーを最後に出力

### 冪等性
- 同じ定義で複数回実行しても問題なし
- 古いメニューは自動削除される設計

### 画像パス解決
- `imagePath` はコミュニティディレクトリ基準（例: `images/admin_menu.png`）
- `deployer.ts` で `path.resolve(communityBasePath, imagePath)` により絶対パスに解決

### テスタビリティ
- `DeployRichMenuContext` により依存性を明示化
- CLI 側がコンテキストを組み立て、`deployRichMenus` は受け取るだけ
- モック可能な設計でユニットテストが容易

---

### 実行結果サマリーの JSON 出力

デプロイ結果を JSON ファイルに出力し、GitHub Actions の artifact として保存することで、管理者が差分を追跡できるようになる。

**出力例 (`richmenu-deploy-result.json`):**
```json
{
  "community": "izu",
  "menus": [
    { "alias": "admin-menu", "richMenuId": "richmenu-xxx", "dbSaved": true, "isDefault": false },
    { "alias": "public-use", "richMenuId": "richmenu-yyy", "dbSaved": true, "isDefault": true },
    { "alias": "public-join", "richMenuId": "richmenu-zzz", "dbSaved": false, "isDefault": false }
  ],
  "timestamp": "2024-01-15T10:30:00.000Z"
}
```

**用途:**
- デプロイ履歴の追跡
- 監査ログとしての活用
- 問題発生時のデバッグ

---

## スコープ外（別Issue候補）

- `LineRichMenuType.USER` の活用（現時点で未使用）
- `src/application/domain/notification/presenter/richmenu/const.ts` の `LINE_RICHMENU` 定数の削除（現時点で未使用）
- `.generated/richmenu.txt` の生成継続（必要であれば別途検討）

---

### 既存コード（参考）
- `scripts/richmenu/*/setup_richmenu.sh` - 現行の手動スクリプト
- `src/application/domain/notification/service.ts` - `switchRichMenuByRole()`
- `src/application/domain/account/community/config/service.ts` - `getLineRichMenuIdByType()`
- `src/infrastructure/prisma/schema.prisma` - `CommunityLineRichMenuConfig`

### 新規作成ファイル
- `src/infrastructure/richmenu/types.ts`
- `src/infrastructure/richmenu/utils.ts`
- `src/infrastructure/richmenu/deployer.ts`
- `src/infrastructure/richmenu/{community}/definitions/*.ts`
- `src/infrastructure/richmenu/{community}/images/*.png`
- `src/infrastructure/richmenu/{community}/index.ts`
- `.github/workflows/deploy-richmenu.yml`
