### ISSUE TITLE
`types/graphql.ts` で古いテーブルクラスがimportされている

### ISSUE THREAD

**Issue by sigma-xing2** [Hopin-inc/civicship-api#62]
下記のようにimportされているが、 `Agenda` などは既に削除されている。
`pnpm gql:generate` でこれらが生成されないようにしたい。

```ts
import { Agenda, City, State, Index, Event, Activity, Like, Comment, Organization, Group, Target, User } from '@prisma/client/index.d';
```

**Comment by 709sakata** [comment]
これで解消した

```
mappers:
  User: "@prisma/client/index.d#User"
  Identity: "@prisma/client/index.d#Identity"
  Community: "@prisma/client/index.d#Community"
  Membership: "@prisma/client/index.d#Membership"
  Wallet: "@prisma/client/index.d#Wallet"
  CurrentPointView: "@prisma/client/index.d#CurrentPointView"
  Opportunity: "@prisma/client/index.d#Opportunity"
  Participation: "@prisma/client/index.d#Participation"
  ParticipationStatusHistory: "@prisma/client/index.d#ParticipationStatusHistory"
  Utility: "@prisma/client/index.d#Utility"
  Transaction: "@prisma/client/index.d#Transaction"
  City: "@prisma/client/index.d#City"
  State: "@prisma/client/index.d#State"

```
